# Generated by Django 5.0.1 on 2024-06-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='proyectos'),
        ),
    ]
