# Generated by Django 5.0.1 on 2024-06-08 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_proyectos_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marca',
            new_name='Modalidad',
        ),
        migrations.RenameField(
            model_name='proyectos',
            old_name='marca',
            new_name='modalidad',
        ),
    ]
