# Generated by Django 5.0.1 on 2024-06-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_proyecto_salario_currency_alter_proyecto_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='salario_currency',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hourly_rate_currency',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True),
        ),
    ]
