# Generated by Django 5.0.1 on 2024-06-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_categoria_remove_proyecto_nuevo_proyecto_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
