# Generated by Django 5.0.1 on 2024-06-16 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_categoria_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='usuario',
            new_name='creator',
        ),
    ]
