# Generated by Django 5.0.1 on 2024-06-16 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_usuario_proyecto_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applied_at',
            new_name='date_applied',
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
    ]
