# Generated by Django 5.0.1 on 2024-06-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='project',
        ),
    ]
